version: '3'
services:
  mfk-stack-ver0.0.1-fluent_d:
    # image: fluent/fluentd:latest
    build: ${PWD}/fluent_d/
    container_name: mfk-stack-ver0.0.1-fluent_d
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./conf:/fluentd/etc
      - ./log:/fluentd/log
    depends_on:
      - mfk-stack-ver0.0.1-mongo
    networks:
      mfk-stack-ver0.0.1:
        ipv4_address: 13.254.249.90
    links:
      - mfk-stack-ver0.0.1-mongo
  mfk-stack-ver0.0.1-nginx_d:
    image: nginx
    container_name: mfk-stack-ver0.0.1-nginx_d
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 13.254.249.90:24224
        tag: nginx.hello0
        fluentd-async-connect: "true"
    depends_on:
      - mfk-stack-ver0.0.1-fluent_d
    networks:
      mfk-stack-ver0.0.1:
        ipv4_address: 13.254.249.89
  
  mfk-stack-ver0.0.1-nginx_d_1:
    image: nginx
    container_name: mfk-stack-ver0.0.1-nginx_d_1
    ports:
      - "81:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 11.254.249.90:24224
        tag: nginx.hello1
        fluentd-async-connect: "true"
    depends_on:
      - mfk-stack-ver0.0.1-fluent_d
    networks:
      mfk-stack-ver0.0.1:
        ipv4_address: 13.254.249.88

  mfk-stack-ver0.0.1-mongo:
    image: mongo
    container_name: mfk-stack-ver0.0.1-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    networks:
      mfk-stack-ver0.0.1:
        ipv4_address: 13.254.249.87
  
  # mfk-stack-ver0.0.1-mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #     ME_CONFIG_MONGODB_SERVER: mfk-stack-ver0.0.1-mongo
  #   depends_on:
  #     - mfk-stack-ver0.0.1-mongo

networks:
  mfk-stack-ver0.0.1:
    ipam:
      driver: default
      config:
        - subnet: 13.254.249.0/24